import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/components/common/Navbar'
import Footer from '@/components/common/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Navbar />
        </nav>
        <main className='min-h-screen'>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
